# Site settings
title: Blog site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; 2016 Harsha Sheshanna
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hsheshanna.github.io" # the base hostname & protocol for your site
twitter_username: harshasheshanna
github_username:  hsheshanna

# Build settings
markdown: kramdown
